
<?php

session_start();

$posted = array();

if (!empty($_SESSION['user_details'])) {

    $posted['firstname'] = $_SESSION['user_details'][0];
    $posted['lastname'] = $_SESSION['user_details'][1];
    $posted['email'] = $_SESSION['user_details'][2];
    $posted['phone'] = $_SESSION['user_details'][3];
    $posted['address1'] = $_SESSION['user_details'][4];
    $posted['city'] = $_SESSION['user_details'][5];
    $posted['zipcode'] = $_SESSION['user_details'][6];
    $posted['state'] = $_SESSION['user_details'][7];
    $posted['country'] = $_SESSION['user_details'][8];
    $posted['txnid'] = $_SESSION['user_details'][9];
    $posted['amount'] = 0;

    if (!empty($_SESSION['cart'])) {
        foreach ($_SESSION['cart'] as $key => $value) {
            $posted['amount'] = $posted['amount'] + ((int) $value[0] * (int) $value[4]);
        }
    }
}

/*

Common Fields Returned in the Success URL
tx: The transaction ID generated by PayPal.
st: The payment status (e.g., "Completed").
amt: The amount paid.
cc: The currency code (e.g., "USD").
item_name: The name of the item purchased.
item_number: The item number or ID.
cm: Custom field data that you sent with the transaction (e.g., order ID).
sig: A signature that can be used to verify the authenticity of the data

 */

?>

<form action="https://secure.paypal.com/uk/cgi-bin/webscr" method="post" name="paypal" id="paypal">
    <!-- Prepopulate the PayPal checkout page with customer details, -->
    <input type="hidden" name="first_name" value="<?php echo $posted['firstname'] ?>">
    <input type="hidden" name="last_name" value="<?php $posted['lastname']?>">
    <input type="hidden" name="email" value="<?php echo $posted['email'] ?>">
    <input type="hidden" name="address1" value="<?php echo $posted['address1'] ?>">
    <input type="hidden" name="city" value="<?php echo $posted['city'] ?>">
    <input type="hidden" name="zip" value="<?php echo $posted['zipcode'] ?>">
    <input type="hidden" name="day_phone_b" value="<?php echo $posted['phone'] ?>">
    <input type="hidden" name="item_number" value="<?php echo $posted['txnid'] ?>">

    <!-- We don't need to use _ext-enter anymore to prepopulate pages -->
    <!-- cmd = _xclick will automatically pre populate pages -->
    <!-- More information: https://www.x.com/docs/DOC-1332 -->
    <input type="hidden" name="cmd" value="_xclick" />
    <input type="hidden" name="business" value="sb-43blmk31028367@business.example.com" />
    <input type="hidden" name="cbt" value="Return to Your Business Name" />
    <input type="hidden" name="currency_code" value="GBP" />

    <!-- Custom value you want to send and process back in the IPN -->
    <input type="hidden" name="custom" value="<?php echo $posted['txnid'] ?>" />

    <input type="hidden" name="amount" value="<?php echo $posted['amount']; ?>" />
    <input type="hidden" name="return" value="http://localhost/shopping-cart/paypal/paypal_success.php"/>
    <input type="hidden" name="cancel_return" value="http://localhost/shopping-cart/paypal/paypal_failure.php" />

    <!-- Where to send the PayPal IPN to. -->
    <input type="hidden" name="notify_url" value="http://http://localhost/shopping-cart/paypal/paypal_IPN.php" />
</form>