<?php 


/*

Common Fields Returned in the Success URL

tx: The transaction ID generated by PayPal.
st: The payment status (e.g., "Completed").
amt: The amount paid.
cc: The currency code (e.g., "USD").
item_name: The name of the item purchased.
item_number: The item number or ID.
cm: Custom field data that you sent with the transaction (e.g., order ID).
sig: A signature that can be used to verify the authenticity of the data

*/

echo "Payment Paypal successful";

if(!empty($_GET['tx']) && $_GET['st'] && $_GET['amt'] && $_GET['item_number'] && $_GET['cm'] && $_GET['sig']){
    echo "<pre>";
    print_r($_GET);
    echo "</pre>";
}

?>